AllCops:
  TargetRubyVersion: 2.3
Rails:
  Enabled: true

# gem 'rubocop-rspec'
require: rubocop-rspec

RSpec/ExpectActual: # bad for routing spec's matcher
  Exclude:
    - 'spec/routing/*'

inherit_from: .rubocop_todo.yml
